### ISSUE TITLE
Plans for compatibility with grunt 1.0?

### ISSUE THREAD

**Issue by wschmrdrNS** [tommcc/grunt-eco#12]
Grunt has been updated to version 1.0; are there any plans to make this package compatible with the newer version of grunt?

**Comment by navitmccaffery** [comment]
I am no longer relying on this plugin, but welcome any pull requests to
make it compatible!

**Comment by wschmrdrNS** [comment]
On initial inspection, nothing in the code on this project looks to be incompatible in accordance with grunt's changelog. We should be able to get away with just changing the dependency on grunt to >=0.4, as per grunt's migration recommendation. I saw there's no "npm test" on this project; is there another means you already have of running the test data?

**Comment by tommcc** [comment]
Fixed by #13
